name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-qemu-action@v2
      with:
        platforms: riscv64,arm64,arm

    - uses: docker/setup-buildx-action@v2

    - name: Build
      run: |
        curl --fail --location --silent --output bob https://function61.com/go/turbobob-latest-linux-amd64 && chmod +x bob
        CI_REVISION_ID="$GITHUB_SHA" ./bob build --publish-artefacts
      env:
        DOCKER_CREDS: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
